# Generated by Django 2.1.7 on 2019-06-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20190619_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.CharField(default='old', max_length=40),
        ),
    ]
