# Generated by Django 2.1.7 on 2019-07-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_notification_send_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='unique_code',
            field=models.IntegerField(default=-1),
        ),
    ]
