# Generated by Django 2.1.7 on 2019-07-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='send_by',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
