# Generated by Django 2.1.7 on 2019-06-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_request_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_item',
            name='requesting_user',
            field=models.CharField(default='initial', max_length=50),
        ),
    ]
