# Generated by Django 2.1.7 on 2019-06-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_request_item_requesting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_item',
            name='first',
            field=models.CharField(default='initial', max_length=50),
        ),
        migrations.AddField(
            model_name='request_item',
            name='last',
            field=models.CharField(default='initial', max_length=50),
        ),
    ]
