# Generated by Django 2.1.7 on 2019-06-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20190614_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='dis_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='request_item',
            name='dis_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='request_item',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
