# Generated by Django 2.1.7 on 2019-06-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20190614_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='dis_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='request_item',
            name='dis_id',
            field=models.IntegerField(null=True),
        ),
    ]
