# Generated by Django 2.1.7 on 2019-06-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20190614_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_discription',
            name='product_name',
            field=models.CharField(default='initial', max_length=40),
        ),
        migrations.AddField(
            model_name='request_item',
            name='product_name',
            field=models.CharField(default='initial', max_length=40),
        ),
    ]
