# Generated by Django 2.1.7 on 2019-08-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_cart_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_item',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
