# Generated by Django 2.1.7 on 2019-08-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_request_item_photo1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_item',
            name='photo1',
        ),
        migrations.AddField(
            model_name='cart',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
